export type Node = {
    /**
     * Node's name used to refer it.
     */
    id: string;
    /**
     * Node's type.
     */
    type: Type;
    /**
     * Human friendly node's description.
     */
    description?: string;
    /**
     * Application, or service technology.
     */
    technology?: string;
    /**
     * Deployment environment for the application, or service.
     */
    deployment?: string;
    /**
     * Node's children.
     */
    nodes?: Node[];
}

/**
 * Node's type.
 */
export enum Type {
    Organisation = "organisation",
    Department = "department",
    Domain = "domain",
    Team = "team",
    Service = "service",
    Application = "application",
    Database = "database",
    Queue = "queue",
}

/**
 * Connection between two Nodes, i.e. graph's edge.
 */
type Link = {
    /**
     * Edge start's Node id.
     */
    from: string;
    /**
     * Edge end's Node id.
     */
    to: string;
    /**
     * Human friendly description of the link between two Nodes.
     */
    description?: string;
    /**
     * Interface technology and protocol, e.g. HTTP/JSON.
     */
    technology?: string;
}

export type graph = {
    nodes: Node[];
    links?: Link[];
}

export type NodeCompositeID = {
    // foo.bar.baz as opposed to ...{id: foo, nodes: [{id: bar, nodes: [{id: baz }...
    composite_id: string;
    // baz
    id: string;
    description: string;
}

export type GroupedNodes = {
    [key in Type]: NodeCompositeID[];
};

function isValidNodeID(id: string) {
    return !id.includes(".")
}

function validNodesID(nodes: Node[]) {
    for (const node of nodes) {
        if (!isValidNodeID(node.id)) {
            return false;
        }
        if (node.nodes !== undefined && !validNodesID(node.nodes)) {
            return false
        }
    }
    return true;
}

/**
 * Defines the graph.
 */
export class Graph {
    nodes: Node[]
    links?: Link[]

    constructor(v: object) {
        const raw: graph = cast(v, r("graph"));

        if (!validNodesID(raw.nodes)) {
            throw new Error("unexpected node id");
        }

        this.nodes = raw.nodes
        this.links = raw.links
    }

    listGroupedNodes(): GroupedNodes {
        // TODO: BFS graph traversal to fill the struct
        return {
            organisation: [],
            application: [],
            database: [],
            department: [],
            domain: [],
            queue: [],
            service: [],
            team: []
        };
    }

    defineC4Diagram(composite_id: string, zoomLevel: string): string {
        const n = this.getNodeByCompositeID(composite_id);
        if (n === undefined) {
            throw Error("node not found")
        }
        return "";
    }

    private getNodeByCompositeID(id: string): Node | undefined {
        // TODO: implement DFS
        return undefined
    }
}

/**
 * GENERATED by https://app.quicktype.io/
 * */
function invalidValue(typ: any, val: any, key: any, parent: any = ''): never {
    const prettyTyp = prettyTypeName(typ);
    const parentText = parent ? ` on ${parent}` : '';
    const keyText = key ? ` for key "${key}"` : '';
    throw Error(`Invalid value${keyText}${parentText}. Expected ${prettyTyp} but got ${JSON.stringify(val)}`);
}

function prettyTypeName(typ: any): string {
    if (Array.isArray(typ)) {
        if (typ.length === 2 && typ[0] === undefined) {
            return `an optional ${prettyTypeName(typ[1])}`;
        } else {
            return `one of [${typ.map(a => {
                return prettyTypeName(a);
            }).join(", ")}]`;
        }
    } else if (typeof typ === "object" && typ.literal !== undefined) {
        return typ.literal;
    } else {
        return typeof typ;
    }
}

function jsonToJSProps(typ: any): any {
    if (typ.jsonToJS === undefined) {
        const map: any = {};
        typ.props.forEach((p: any) => map[p.json] = {key: p.js, typ: p.typ});
        typ.jsonToJS = map;
    }
    return typ.jsonToJS;
}

function transform(val: any, typ: any, getProps: any, key: any = '', parent: any = ''): any {
    function transformPrimitive(typ: string, val: any): any {
        if (typeof typ === typeof val) return val;
        return invalidValue(typ, val, key, parent);
    }

    function transformUnion(typs: any[], val: any): any {
        // val must validate against one typ in typs
        const l = typs.length;
        for (let i = 0; i < l; i++) {
            const typ = typs[i];
            try {
                return transform(val, typ, getProps);
            } catch (_) {
            }
        }
        return invalidValue(typs, val, key, parent);
    }

    function transformEnum(cases: string[], val: any): any {
        if (cases.indexOf(val) !== -1) return val;
        return invalidValue(cases.map(a => {
            return l(a);
        }), val, key, parent);
    }

    function transformArray(typ: any, val: any): any {
        // val must be an array with no invalid elements
        if (!Array.isArray(val)) return invalidValue(l("array"), val, key, parent);
        return val.map(el => transform(el, typ, getProps));
    }

    function transformDate(val: any): any {
        if (val === null) {
            return null;
        }
        const d = new Date(val);
        if (isNaN(d.valueOf())) {
            return invalidValue(l("Date"), val, key, parent);
        }
        return d;
    }

    function transformObject(props: { [k: string]: any }, additional: any, val: any): any {
        if (val === null || typeof val !== "object" || Array.isArray(val)) {
            return invalidValue(l(ref || "object"), val, key, parent);
        }
        const result: any = {};
        Object.getOwnPropertyNames(props).forEach(key => {
            const prop = props[key];
            const v = Object.prototype.hasOwnProperty.call(val, key) ? val[key] : undefined;
            result[prop.key] = transform(v, prop.typ, getProps, key, ref);
        });
        Object.getOwnPropertyNames(val).forEach(key => {
            if (!Object.prototype.hasOwnProperty.call(props, key)) {
                result[key] = transform(val[key], additional, getProps, key, ref);
            }
        });
        return result;
    }

    if (typ === "any") return val;
    if (typ === null) {
        if (val === null) return val;
        return invalidValue(typ, val, key, parent);
    }
    if (typ === false) return invalidValue(typ, val, key, parent);
    let ref: any = undefined;
    while (typeof typ === "object" && typ.ref !== undefined) {
        ref = typ.ref;
        typ = typeMap[typ.ref];
    }
    if (Array.isArray(typ)) return transformEnum(typ, val);
    if (typeof typ === "object") {
        return typ.hasOwnProperty("unionMembers") ? transformUnion(typ.unionMembers, val)
            : typ.hasOwnProperty("arrayItems") ? transformArray(typ.arrayItems, val)
                : typ.hasOwnProperty("props") ? transformObject(getProps(typ), typ.additional, val)
                    : invalidValue(typ, val, key, parent);
    }
    // Numbers can be parsed by Date but shouldn't be.
    if (typ === Date && typeof val !== "number") return transformDate(val);
    return transformPrimitive(typ, val);
}

function cast<T>(val: any, typ: any): T {
    return transform(val, typ, jsonToJSProps);
}

function l(typ: any) {
    return {literal: typ};
}

function a(typ: any) {
    return {arrayItems: typ};
}

function u(...typs: any[]) {
    return {unionMembers: typs};
}

function o(props: any[], additional: any) {
    return {props, additional};
}

function r(name: string) {
    return {ref: name};
}

const typeMap: any = {
    "graph": o([
        {json: "links", js: "links", typ: u(undefined, a(r("Link")))},
        {json: "nodes", js: "nodes", typ: a(r("Node"))},
    ], "any"),
    "Link": o([
        {json: "description", js: "description", typ: u(undefined, "")},
        {json: "from", js: "from", typ: ""},
        {json: "technology", js: "technology", typ: u(undefined, "")},
        {json: "to", js: "to", typ: ""},
    ], "any"),
    "Node": o([
        {json: "deployment", js: "deployment", typ: u(undefined, "")},
        {json: "description", js: "description", typ: u(undefined, "")},
        {json: "id", js: "id", typ: ""},
        {json: "nodes", js: "nodes", typ: u(undefined, a(r("Node")))},
        {json: "technology", js: "technology", typ: u(undefined, "")},
        {json: "type", js: "type", typ: r("Type")},
    ], "any"),
    "Type": [
        "application",
        "database",
        "department",
        "domain",
        "organisation",
        "queue",
        "service",
        "team",
    ],
};